[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = [".env"]

[dev]
  framework = "#custom"
  command = "react-scripts start"
  targetPort = 3000
  port = 8888
  publish = "build"
  functions = "netlify/functions"
  autoLaunch = true
  functionsPort = 9999

[forms]
  [forms."login-form"]
    email = "jvab5899@gmail.com" 